# Generated by Django 4.1.4 on 2023-01-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_posts_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user_id',
            new_name='user',
        ),
    ]
