# Generated by Django 4.1.4 on 2023-01-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_user_id_posts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
    ]
