# Generated by Django 4.1.4 on 2023-01-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
