# Generated by Django 4.1.3 on 2023-02-03 06:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_posts_image_alter_posts_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_photo',
            field=models.ImageField(default='group_photo/image.jpg', upload_to=core.models.image_path),
        ),
    ]
