# Generated by Django 4.1.4 on 2023-02-04 09:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_groups_group_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='posts/image.jpg', upload_to=core.models.image_path),
        ),
    ]
