# Generated by Django 4.1.4 on 2023-02-04 09:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile/user.png', upload_to=core.models.image_path),
        ),
    ]
