# Generated by Django 4.1.3 on 2023-02-05 07:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile/user.png', upload_to=core.models.profile_img_path),
        ),
    ]
